apiVersion: v1
kind: ConfigMap
metadata:
  name: donation-processor-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8081"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__QueueName: "donation-received-queue"