apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-processor
  namespace: hackathon-9nett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation-processor
  template:
    metadata:
      labels:
        app: donation-processor
    spec:
      containers:
        - name: donation-processor
          image: donation-processor:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: donation-processor-config