apiVersion: v1
kind: Service
metadata:
  name: donation-processor-worker-service
  namespace: hackathon-9nett
spec:
  selector:
    app: donation-processor-worker
  ports:
    - name: http
      protocol: TCP
      port: 80